name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - changed-files
      - checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@gate-telemetry-summarize
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
  changed-files:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/changed-files.yaml@gate-telemetry-summarize
    with:
      files_yaml: |
        test_cpp:
          - '**'
          - '!.pre-commit-config.yaml'
          - '!README.md'
          - '!docs/**'
          - '!python/**'
        test_python:
          - '**'
          - '!.pre-commit-config.yaml'
          - '!README.md'
          - '!docs/**'
  checks:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@gate-telemetry-summarize
    with:
      enable_check_generated_files: false
